const PROJECTS = [
  {
    id: "01",
    title: "Automatización Calendar",
    description:
      "Sincronización en tiempo real entre Turitop y Google Calendar con notificaciones automáticas a guías.",
    icon: "📅",
    apis: ["Turitop", "Google Calendar", "n8n", "Email"],
    steps: [
      {
        id: "c1",
        type: "trigger",
        title: "Webhook Turitop",
        subtitle:
          "Recibe eventos de reserva, cancelación o modificación desde Turitop API",
        api: ["Turitop", "n8n"],
        details: [
          "Método: POST /webhook/turitop",
          "Auth: API Key header",
          "Eventos: booking, cancel, modify",
        ],
      },
      {
        id: "c2",
        type: "action",
        title: "Parsear Título Evento",
        subtitle:
          "Extrae y decodifica: código tour, número de personas, guía confirmado y guías pendientes entre paréntesis",
        api: ["n8n"],
        details: [
          "Formato título: [CódigoTour] [Personas] [Guía] ([Pendientes])",
          "WT = Wine Tour Madrid",
          "WTR = Wine Tour Ribera del Duero",
          "TT = Tapas Tour Tarde",
          "TM = Tapas Tour Mañana",
          "CCATA = Curso de Cata",
          "*P = Privados (excluidos, gestión manual)",
          "Guías confirmados: sin paréntesis",
          "Guías pendientes: entre ()",
          "Códigos guías: TM 23=Carlos, TT 23=Carlos, TM 24=Noemí, TT 24=Carlos, TM 25=Noemí, TT 25=Noemí, TM 26=Muna, TT 26=Yolanda, TM 27=Eva, TT 27=Carlos, TM 28=Carlos, TT 28=Noemí, TM 29=Noemí, TT 29=Carlos, TM 30=Carlos, TT 30=Carlos, TM 01=Eva, TT 01=Carlos, TM 02=Noemí, TT 02=Noemí, TM 03=Rocio, TT 03=Yolanda",
          "Output: {tour, personas, guia_confirmado, guias_pendientes[]}",
        ],
      },
      {
        id: "c3",
        type: "action",
        title: "Actualizar Google Calendar",
        subtitle:
          "Registra el cambio y almacena notas especiales en descripción",
        api: ["Google Calendar"],
        details: [
          "Operación: Update Event",
          "Campos: title, description",
        ],
      },
      {
        id: "c4",
        type: "decision",
        title: "¿Cupo lleno?",
        subtitle: "Compara personas actuales vs. cupo máximo",
        api: ["n8n"],
        details: ["Condición: personas >= cupo_max"],
      },
      {
        id: "c5-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Cupo lleno",
        title: "Notificar Cierre",
        subtitle:
          "Alerta al equipo para cerrar actividad si es necesario",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Asunto: [URGENTE] Cupo lleno",
          "→ Continúa a: ¿Guía pendiente?",
        ],
      },
      {
        id: "c5-no",
        type: "branch_no",
        branchLabel: "NO — Hay espacio",
        title: "Continuar flujo",
        subtitle: "El flujo continúa hacia la siguiente validación",
        api: ["n8n"],
        details: [
          "→ Continúa a: ¿Guía pendiente?",
        ],
      },
      {
        id: "c6",
        type: "decision",
        title: "¿Guía pendiente?",
        subtitle: "Detecta guías sin confirmar entre paréntesis",
        api: ["n8n"],
        details: ['Regex: \\([A-Z]{2} \\d{2}\\)'],
      },
      {
        id: "c7-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Guía pendiente",
        title: "Solicitar Confirmación",
        subtitle: "Envía email al siguiente guía esperando respuesta",
        api: ["Email", "n8n"],
        details: [
          "Espera: Webhook 48h",
          "→ Si confirma → Confirmar Guía",
          "→ Si no responde en 48h → Siguiente Guía (loop)",
        ],
      },
      {
        id: "c7-no",
        type: "branch_no",
        branchLabel: "NO — Guías confirmados",
        title: "Continuar flujo",
        subtitle: "Se salta la espera de confirmación de guías",
        api: ["n8n"],
        details: [
          "→ Salta a: Siguiente paso",
        ],
      },
      {
        id: "c8",
        type: "decision",
        title: "¿Confirmó el guía?",
        subtitle: "Espera respuesta del guía tras solicitud",
        api: ["n8n"],
        details: ["Espera Webhook respuesta (max 48h)"],
      },
      {
        id: "c9-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Confirmado",
        title: "Confirmar Guía",
        subtitle: "Quita paréntesis del código guía en título",
        api: ["Google Calendar"],
        details: [
          "Actualizar título: remove paréntesis",
          "→ Continúa a: Notificar Confirmación",
        ],
      },
      {
        id: "c9-no",
        type: "branch_no",
        branchLabel: "NO — Sin respuesta",
        title: "Siguiente Guía",
        subtitle: "Vuelve a evaluar siguiente guía en cola",
        api: ["n8n"],
        details: [
          "→ Vuelve a Solicitar Confirmación (loop)",
        ],
      },
      {
        id: "c10",
        type: "notification",
        title: "Notificar Confirmación",
        subtitle: "Informa al equipo del nuevo guía confirmado",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Contenido: Nuevo guía confirmado",
        ],
      },
    ],
  },
  {
    id: "02",
    title: "Automatización Email",
    description:
      "Asistente IA que responde automáticamente preguntas basadas en knowledge base.",
    icon: "✉️",
    apis: ["Email", "Google Docs", "n8n", "IA"],
    steps: [
      {
        id: "e1",
        type: "trigger",
        title: "Email Trigger",
        subtitle: "Recibe emails en info@gourmetmadrid.com",
        api: ["Email", "n8n"],
        details: [
          "Cuenta: info@gourmetmadrid.com",
          "Filtro: Sin leer, no spam",
        ],
      },
      {
        id: "e2",
        type: "decision",
        title: "¿Email válido?",
        subtitle: "Filtra emails según lista de exclusión (spam, newsletters)",
        api: ["n8n"],
        details: ["Filtros: spam, newsletters, blacklist"],
      },
      {
        id: "e2-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Válido",
        title: "LLM Agent",
        subtitle: "Analiza la pregunta consultando la knowledge base",
        api: ["IA", "Google Docs"],
        details: [
          "Contexto: Google Docs (Drive)",
          "Prompt: Responde basándote en KB",
          "→ Continúa a: ¿Puede responder?",
        ],
      },
      {
        id: "e2-no",
        type: "branch_no",
        branchLabel: "NO — Spam/Inválido",
        title: "Marcar como leído",
        subtitle: "Se ignora el email sin responder",
        api: ["Email"],
        details: ["Acción: Marcar como leído en inbox"],
      },
      {
        id: "e3",
        type: "decision",
        title: "¿Puede responder?",
        subtitle: "Evalúa si la KB tiene información suficiente",
        api: ["IA", "n8n"],
        details: [
          "Si confianza > 80% → Responder",
          "Si confianza < 80% → Notificar interno",
        ],
      },
      {
        id: "e3-yes",
        type: "branch_yes",
        branchLabel: "SÍ — KB suficiente",
        title: "Responder Cliente",
        subtitle: "Envía respuesta automática desde info@gourmetmadrid.com",
        api: ["Email", "IA"],
        details: [
          "Para: {email_cliente}",
          "Plantilla: Respuesta IA + firma",
        ],
      },
      {
        id: "e3-no",
        type: "branch_no",
        branchLabel: "NO — Falta info",
        title: "Notificar Interno",
        subtitle: "Alerta para que un humano responda manualmente",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Contenido: Email original + marca urgente",
        ],
      },
    ],
  },
  {
    id: "03",
    title: "Clasificación Emails",
    description:
      "Clasifica automáticamente tickets de Turitop en carpetas por día/mes/año.",
    icon: "📁",
    apis: ["Email", "n8n"],
    steps: [
      {
        id: "cl1",
        type: "trigger",
        title: "Email Receive",
        subtitle: "Recibe nuevo email en la bandeja de entrada",
        api: ["Email", "n8n"],
        details: [
          "Opción A: Gmail - Cuenta dedicada",
          "Opción B: IMAP - Servidor",
        ],
      },
      {
        id: "cl2",
        type: "decision",
        title: "¿Es ticket Turitop?",
        subtitle: "Detecta emails del sistema de reservas",
        api: ["n8n"],
        details: [
          "Filtro: From @turitop.com",
          "Asunto: Booking confirmation, cancel...",
        ],
      },
      {
        id: "cl2-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Ticket Turitop",
        title: "Extraer Fecha",
        subtitle: "Obtiene fecha para clasificar",
        api: ["n8n"],
        details: [
          "Input: Fecha reserva / timestamp",
          "Output: YYYY/MM/DD",
          "→ Continúa a: Mover a Carpeta",
        ],
      },
      {
        id: "cl2-no",
        type: "branch_no",
        branchLabel: "NO — Otro email",
        title: "Otro email",
        subtitle: "No se procesa, permanece en inbox",
        api: [],
      },
      {
        id: "cl3",
        type: "action",
        title: "Mover a Carpeta",
        subtitle: "Clasifica en carpeta según fecha",
        api: ["Email"],
        details: [
          "Gmail: Etiquetas año/mes/día",
          "IMAP: Turitop/2025/05/11",
        ],
      },
    ],
  },
  {
    id: "04",
    title: "Panel Rentabilidad",
    description:
      "Dashboard Next.js + React para análisis de rentabilidad por tour y período.",
    icon: "📊",
    apis: ["Turitop", "Next.js"],
    tabs: [
      {
        id: "summary",
        name: "Resumen Global",
        icon: "📈",
        items: [
          { label: "Filtro selector de fechas", type: "Required" },
          { label: "Facturación Total", type: "Sum" },
          { label: "Gasto Total", type: "Sum" },
          { label: "Beneficio Total", type: "Calc" },
          { label: "Número de Reservas", type: "Count" },
          { label: "Número de Personas", type: "Sum" },
          { label: "Ratio Personas/Reserva", type: "Calc" },
        ],
      },
      {
        id: "by-tour",
        name: "Por Tour",
        icon: "🎯",
        items: [
          { label: "Selector de Tour", type: "Required" },
          { label: "Selector de fecha", type: "Required" },
          { label: "Facturación Tour", type: "Filter" },
          { label: "Gasto Tour", type: "Filter" },
          { label: "Beneficio Tour", type: "Calc" },
          { label: "Nº Reservas Tour", type: "Filter" },
          { label: "Nº Personas Tour", type: "Filter" },
          { label: "Ratio Personas/Reserva", type: "Calc" },
        ],
      },
    ],
    models: [
      {
        name: "Reservas (Turitop)",
        icon: "📋",
        fields: [
          { name: "id", type: "string" },
          { name: "tour_code", type: "WT, TT, TM..." },
          { name: "date", type: "date" },
          { name: "people", type: "number" },
          { name: "total_price", type: "number" },
          { name: "status", type: "confirmed/cancelled" },
        ],
      },
      {
        name: "Gastos (Manual)",
        icon: "💰",
        fields: [
          { name: "id", type: "string" },
          { name: "tour_code", type: "WT, TT, TM..." },
          { name: "amount", type: "number" },
          { name: "category", type: "guías, transporte..." },
          { name: "date", type: "date" },
          { name: "description", type: "string" },
        ],
      },
    ],
  },
];

export default PROJECTS;
