const PROJECTS = [
  {
    id: "01",
    title: "Automatización Calendar",
    description:
      "Sincronización en tiempo real entre Turitop y Google Calendar con notificaciones automáticas a guías. Dispone de dos puntos de entrada: webhook Turitop y modificaciones detectadas desde Clasificación Emails (Get Your Guide).",
    icon: "📅",
    apis: ["Turitop", "Google Calendar", "n8n", "Email", "WhatsApp"],
    steps: [
      {
        id: "c-entry-mod",
        type: "trigger",
        title: "Webhook Modificación desde Clasificación",
        subtitle:
          "Punto de entrada alternativo. Recibe datos desde cl-calendar del flujo Clasificación cuando se detecta una modificación vía Get Your Guide.",
        api: ["n8n"],
        details: [
          "Disparado desde: cl-calendar (Flujo Clasificación Emails)",
          "Body: { codigo_reserva, tour_code, personas_nuevas, fecha, actividad }",
          "El código de reserva es el mismo que el del email Turitop original",
          "Este webhook contiene los DATOS CORREGIDOS (2º email Turitop)",
          "El 1er email Turitop ya fue marcado como 'superseded' en la BD",
        ],
        continuation: "→ Siguiente: Parsear Título Evento",
      },
      {
        id: "c1",
        type: "trigger",
        title: "Webhook Turitop",
        subtitle:
          "Recibe eventos de reserva, cancelación o modificación desde Turitop API. Los datos de cupo total y cupo por guía llegan desde Turitop.",
        api: ["Turitop", "n8n"],
        details: [
          "Método: POST /webhook/turitop",
          "Auth: API Key header",
          "Eventos: booking, cancel, modify",
          "Datos recibidos: tour_code, personas, guías, cupo_total, cupo_por_guía",
          "cupo_total = 30 (capacidad máxima actividad)",
          "cupo_por_guía = máx personas por guía (ej: 15)",
        ],
        continuation: "→ Siguiente: Parsear Título Evento",
      },
      {
        id: "c2",
        type: "action",
        title: "Parsear Título Evento",
        subtitle:
          "Extrae y decodifica: código tour, número de personas, guía confirmado y guías pendientes entre paréntesis",
        api: ["n8n"],
        details: [
          "Formato título: [CódigoTour] [Personas] [Guía] ([Pendientes])",
          "",
          "Códigos Tour:",
          "  WT   = Wine Tour a bodegas de Madrid",
          "  WTR  = Wine Tour a Ribera del Duero",
          "  TT   = Tapas Tour Tarde",
          "  TM   = Tapas Tour Mañana",
          "  CCATA = Curso de Cata",
          "  *P   = Privados (excluidos, gestión manual)",
          "",
          "Guías:",
          "  (a) Guía confirmado (sin paréntesis) = guía principal asignado",
          "  (b) Guías pendientes (entre paréntesis) = lista de espera sin confirmar",
          "",
          "Códigos de Guía:",
          "  TM 23 = Carlos | TT 23 = Carlos",
          "  TM 24 = Noemí (Carlos reserva privados alemanes)",
          "  TT 24 = Carlos",
          "  TM 25 = Noemí | TT 25 = Noemí",
          "  TM 26 = Muna | TT 26 = Yolanda",
          "  TM 27 = Eva | TT 27 = Carlos",
          "  TM 28 = Carlos | TT 28 = Noemí",
          "  TM 29 = Noemí | TT 29 = Carlos",
          "  TM 30 = Carlos | TT 30 = Carlos",
          "  TM 01 = Eva | TT 01 = Carlos",
          "  TM 02 = Noemí | TT 02 = Noemí",
          "  TM 03 = Rocio | TT 03 = Yolanda",
          "",
          "Output: {tour, personas, guia_confirmado, guias_pendientes[]}",
        ],
        continuation: "→ Siguiente: Buscar Evento en Sheet",
      },
      {
        id: "c2-buscar-evento",
        type: "action",
        title: "Buscar Evento en Sheet",
        subtitle:
          "Busca el evento en Sheet Eventos por product_short_id + fecha. Si existe, es que ya se recibió un webhook previo.",
        api: ["Google Sheets", "n8n"],
        details: [
          "Lookup en Sheet Eventos por product_short_id + fecha",
          "Si existe → evento ya creado (Turitop2 o modificación)",
          "Si no existe → evento nuevo (Turitop1)",
        ],
        continuation: "→ Siguiente: Buscar Reserva en Sheet",
      },
      {
        id: "c2-buscar-reserva",
        type: "action",
        title: "Buscar Reserva en Sheet",
        subtitle:
          "Busca en Sheet reservas si este booking_id ya fue procesado (Turitop2 con datos corregidos).",
        api: ["Google Sheets", "n8n"],
        details: [
          "Lookup en Sheet reservas por booking_id",
          "Si existe → es Turitop2: mismo booking_id llegó antes con otros datos",
          "  Ej: G193-260607-4 llegó 1ª vez con 4 pax, ahora llega con 5 pax",
          "  Se actualiza el total restando el anterior y sumando el nuevo",
          "Si no existe → es Turitop1: reserva nueva, se suma al total",
          "Tras el lookup de Turitop1 (4 pax) llega GYG y luego Turitop2 (5 pax)",
        ],
        continuation: "→ Siguiente: ¿Booking duplicado?",
      },
      {
        id: "c2-duplicado",
        type: "decision",
        title: "¿Booking duplicado?",
        subtitle:
          "Si el booking_id ya existe en reservas, es un reemplazo (Turitop2). Se actualiza el total con el delta entre old y new.",
        api: ["n8n"],
        details: [
          "esBookingDuplicado = true → Calcular Cupos: updatedTotal = currentTotal - originalPersonas + newPersonas",
          "esBookingDuplicado = false → Registrar nueva reserva, sumar al total: updatedTotal = currentTotal + newPersonas",
          "Ambos caminos convergen en Calcular Cupos y continúan igual",
        ],
      },
      {
        id: "c2-duplicado-si",
        type: "branch_yes",
        branchLabel: "SÍ — Reemplazo",
        title: "Actualizar total sin duplicar",
        subtitle:
          "Booking_id ya existente. Se calcula el delta y se actualiza el total del evento.",
        api: ["n8n"],
        continuation: "→ Siguiente: Calcular Cupos (delta)",
      },
      {
        id: "c2-duplicado-no",
        type: "branch_no",
        branchLabel: "NO — Nuevo",
        title: "Registrar y sumar",
        subtitle:
          "Booking_id nuevo. Se añade registro en la hoja de reservas y suma al total del evento.",
        api: ["Google Sheets", "n8n"],
        continuation: "→ Siguiente: Registrar Reserva + Calcular Cupos",
      },
      {
        id: "c3",
        type: "action",
        title: "Actualizar Google Calendar",
        subtitle:
          "Registra el cambio y almacena notas especiales en descripción",
        api: ["Google Calendar"],
        details: [
          "Operación: Update Event",
          "Campos: title, description",
        ],
        continuation: "→ Siguiente: ¿Cupo total ≥ 30?",
      },
      {
        id: "c4-a",
        type: "decision",
        title: "¿Cupo total ≥ 30?",
        subtitle: "Compara personas actuales vs cupo total de la actividad (30)",
        api: ["n8n"],
        details: ["Condición: personas >= cupo_total (30)"],
      },
      {
        id: "c5-a-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Cupo completo",
        title: "Notificar Cierre",
        subtitle: "Alerta al equipo para cerrar la actividad manualmente en Turitop",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Asunto: [URGENTE] Cupo completo — cerrar actividad en Turitop",
        ],
        continuation: "→ Siguiente: ¿Cupo por guía?",
      },
      {
        id: "c5-a-no",
        type: "branch_no",
        branchLabel: "NO — Hay disponibilidad",
        title: "Continuar flujo",
        subtitle: "No se ha superado el cupo total, se continúa con la siguiente validación",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Cupo por guía?",
      },
      {
        id: "c4-b",
        type: "decision",
        title: "¿Cupo por guía superado?",
        subtitle: "Compara personas totales vs cupo máximo por guía (ej: 15)",
        api: ["n8n"],
        details: ["Condición: personas > cupo_por_guía (ej: 15 por guía)"],
      },
      {
        id: "c5-b-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Necesita más guías",
        title: "Iniciar proceso guía",
        subtitle: "Se ha superado el cupo por guía. Se notifica internamente y se inicia el proceso de contacto con el siguiente guía",
        api: ["n8n", "Email", "WhatsApp"],
        details: [
          "Notificar internamente: 'Superado cupo guía para [tour] [fecha]'",
          "Contactar al siguiente guía de la lista (pendientes entre paréntesis)",
          "Canal: WhatsApp (Evolution API) o Email",
          "Registrar en BD: {guía, tour, fecha, timestamp_envío, estado: pendiente}",
          "Esperar respuesta via Webhook Respuesta Guía",
        ],
        continuation: "→ Siguiente: ¿Guía pendiente?",
      },
      {
        id: "c5-b-no",
        type: "branch_no",
        branchLabel: "NO — Cupo ok",
        title: "Continuar flujo",
        subtitle: "No se ha superado el cupo por guía",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Guía pendiente?",
      },
      {
        id: "c6",
        type: "decision",
        title: "¿Guía pendiente?",
        subtitle: "Detecta si hay guías sin confirmar entre paréntesis en el título",
        api: ["n8n"],
        details: ['Regex: \\([A-Z]{2} \\d{2}\\) para detectar guías pendientes'],
      },
      {
        id: "c7-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Hay pendientes",
        title: "Solicitar Confirmación",
        subtitle: "Envía mensaje al siguiente guía de la lista (WhatsApp o Email) y espera respuesta",
        api: ["Email", "WhatsApp", "n8n"],
        details: [
          "Canal: WhatsApp (Evolution API) o Email",
          "Registrar en BD: timestamp_envío, guía, tour, estado=pendiente",
          "Timeout configurable: 6h / 12h / 24h / 48h",
          "Cron cada 1h contrasta timestamp vs hora actual",
          "JS Code: if (now - timestamp_envío >= timeout_config) → timeout",
        ],
        continuation: "→ Continúa en: Respuesta Guía",
      },
      {
        id: "c7-no",
        type: "branch_no",
        branchLabel: "NO — Todos confirmados",
        title: "Continuar flujo",
        subtitle: "Todos los guías están confirmados, no hay pendientes",
        api: ["n8n"],
        continuation: "◼ Finaliza aquí",
      },
    ],
  },
  {
    id: "02",
    title: "Automatización Email",
    description:
      "Asistente IA que responde automáticamente preguntas basadas en knowledge base.",
    icon: "✉️",
    apis: ["Email", "Google Docs", "n8n", "IA"],
    steps: [
      {
        id: "e1",
        type: "trigger",
        title: "Email Trigger",
        subtitle: "Recibe emails en info@gourmetmadrid.com",
        api: ["Email", "n8n"],
        details: [
          "Cuenta: info@gourmetmadrid.com",
          "Filtro: Sin leer, no spam",
        ],
        continuation: "→ Siguiente: ¿Email válido?",
      },
      {
        id: "e2",
        type: "decision",
        title: "¿Email válido?",
        subtitle: "Filtra emails según lista de exclusión (spam, newsletters)",
        api: ["n8n"],
        details: ["Filtros: spam, newsletters, blacklist"],
      },
      {
        id: "e2-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Válido",
        title: "LLM Agent",
        subtitle: "Analiza la pregunta consultando la knowledge base",
        api: ["IA", "Google Docs"],
        details: [
          "Contexto: Google Docs (Drive)",
          "Prompt: Responde basándote en KB",
        ],
        continuation: "→ Siguiente: ¿Puede responder?",
      },
      {
        id: "e2-no",
        type: "branch_no",
        branchLabel: "NO — Spam/Inválido",
        title: "Marcar como leído",
        subtitle: "Se ignora el email sin responder",
        api: ["Email"],
        details: ["Acción: Marcar como leído en inbox"],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "e3",
        type: "decision",
        title: "¿Puede responder?",
        subtitle: "Evalúa si la KB tiene información suficiente",
        api: ["IA", "n8n"],
        details: [
          "Si confianza > 80% → Responder",
          "Si confianza < 80% → Notificar interno",
        ],
      },
      {
        id: "e3-yes",
        type: "branch_yes",
        branchLabel: "SÍ — KB suficiente",
        title: "Responder Cliente",
        subtitle: "Envía respuesta automática desde info@gourmetmadrid.com",
        api: ["Email", "IA"],
        details: [
          "Para: {email_cliente}",
          "Plantilla: Respuesta IA + firma",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "e3-no",
        type: "branch_no",
        branchLabel: "NO — Falta info",
        title: "Notificar Interno",
        subtitle: "Alerta para que un humano responda manualmente",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Contenido: Email original + marca urgente",
        ],
        continuation: "◼ Finaliza aquí",
      },
    ],
  },
  {
    id: "03",
    title: "Clasificación Emails",
    description:
      "Clasifica emails de Turitop por día y actividad, procesa modificaciones de Get Your Guide, Civitatis y Viator con LLM (Gemini), " +
      "concilia reservas duplicadas (superseded/replace) y actualiza Calendar automáticamente via webhook calendar-mod.",
    icon: "📁",
    apis: ["Email", "n8n", "IA", "n8n_database", "Google Calendar"],
    steps: [
      // ═══════════════════════════════════════════════════════
      // SECCIÓN 1: RECEPCIÓN Y FILTRADO
      // ═══════════════════════════════════════════════════════
      {
        id: "cl1",
        type: "trigger",
        title: "Email Receive",
        subtitle: "Recibe nuevo email en la bandeja de entrada",
        api: ["Email", "n8n"],
        details: [
          "Opción A: Gmail - Cuenta dedicada",
          "Opción B: IMAP - Servidor",
        ],
        continuation: "→ Siguiente: ¿Es ticket Turitop?",
      },
      {
        id: "cl2",
        type: "decision",
        title: "¿Es ticket Turitop?",
        subtitle: "Detecta emails del sistema de reservas Turitop",
        api: ["n8n"],
        details: [
          "Filtro: From @turitop.com",
          "Asunto: Booking confirmation, cancel, modify...",
        ],
      },
      {
        id: "cl2-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Ticket Turitop",
        title: "Es Turitop",
        subtitle: "El email es de Turitop. Se procede a clasificar por día y actividad.",
        api: ["n8n"],
        continuation: "→ Siguiente: Extraer Fecha y Actividad",
      },
      {
        id: "cl2-no",
        type: "branch_no",
        branchLabel: "NO — No es Turitop",
        title: "Evaluar otras plataformas",
        subtitle: "No es Turitop. Se comprueba si es email de Get Your Guide, Civitatis o Viator (modificaciones/cancelaciones).",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Es Get Your Guide?",
      },

      // ═══════════════════════════════════════════════════════
      // SECCIÓN 2: CLASIFICACIÓN POR DÍAS Y ACTIVIDADES
      // ═══════════════════════════════════════════════════════
      {
        id: "cl-divider-1",
        type: "divider",
        title: "📂 Sección 2 — Clasificación por Días y Actividades",
      },
      {
        id: "cl3",
        type: "action",
        title: "Extraer Fecha y Actividad",
        subtitle:
          "Obtiene el día del tour y el código de actividad desde el contenido del email. Consulta la nomenclatura del calendario/Excel compartido.",
        api: ["n8n"],
        details: [
          "Input: cuerpo del email Turitop",
          "Extraer: día del tour, código de actividad (WT, TT, TM, WTR, CCATA)",
          "Consultar nomenclatura oficial del calendario compartido",
          "Output: { dia: 1, codigo_actividad: 'WT', fecha: '2025/06/08' }",
          "Si hay múltiples actividades el mismo día, cada una tiene su propia carpeta",
        ],
        continuation: "→ Siguiente: Clasificar por Día-Actividad",
      },
      {
        id: "cl4",
        type: "action",
        title: "Clasificar por Día-Actividad",
        subtitle:
          "Copia el email (no lo mueve) a la carpeta del día-actividad correspondiente. El original permanece en inbox con etiqueta 'Recibidos'.",
        api: ["Email", "n8n"],
        details: [
          "Acción: COPY (no MOVE)",
          "Destino 1: Bandeja de entrada — etiqueta 'Recibidos'",
          "Destino 2: Label Gmail {Año}/{nº-día}-{CódigoActividad}",
          "Ejemplo: Turitop/2026/06/10-WT , Turitop/2026/06/10-TT",
          "Gmail: múltiples labels (INBOX + label día-actividad)",
          "Nomenclatura: Turitop/{YYYY}/{MM}/{day_number}-{tour_code}",
        ],
        continuation: "→ Siguiente: ¿Es reemplazo de reserva modificada?",
      },

      // ═══════════════════════════════════════════════════════
      // SECCIÓN 3: VERIFICACIÓN DE REEMPLAZO (Turitop2)
      // ═══════════════════════════════════════════════════════
      {
        id: "cl-divider-2",
        type: "divider",
        title: "🔄 Sección 3 — Verificación de Reemplazo (2º email Turitop)",
      },
      {
        id: "cl-replace",
        type: "decision",
        title: "¿Es reemplazo de reserva modificada?",
        subtitle:
          "Busca en Sheet reservas si existe un registro con mismo customer_name + tour_code + status=superseded.",
        api: ["n8n", "Google Sheets"],
        details: [
          "Orden real emails: Turitop1 + Webhook (4 pax) → Turitop2 + Webhook (5 pax) → GYG mod",
          "El 2º webhook Turitop (5 pax) llega antes que el email GYG",
          "Calendar Sync detecta booking_id duplicado y calcula el delta automáticamente",
          "Cuando llega el email, la clasificación detecta el cambio vía GYG",
          "Lookup en Sheet reservas: customer_name + status=superseded",
        ],
      },
      {
        id: "cl-replace-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Es reemplazo",
        title: "Llamar webhook calendar-mod",
        subtitle:
          "Se llama a calendar-mod por si Turitop2 no llegó antes (fallback). La actualización principal ya la hizo Calendar Sync al detectar el duplicado.",
        api: ["n8n", "Google Calendar"],
        details: [
          "HTTP POST a /webhook/calendar-mod con datos del 2º email",
          "Body: { booking_id, tour_code, event_date, people, customer_name, event_type: 'modify' }",
          "Calendar-mod es FALLBACK: si Turitop2 no llegó via webhook, esta llamada lo procesa",
          "Normalmente Turitop2 ya fue procesado por Calendar Sync (detección de duplicados)",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "cl-replace-no",
        type: "branch_no",
        branchLabel: "NO — Reserva normal",
        title: "Reserva original sin modificación",
        subtitle: "No hay modificaciones previas. Este es el primer email Turitop para esta reserva.",
        api: ["Google Sheets"],
        details: [
          "Sheet reservas: nuevo registro con status=active, version=1",
          "No se necesita actualizar Calendar (webhook Turitop ya lo maneja)",
          "El flujo Calendar Sync procesa el webhook de Turitop directamente",
        ],
        continuation: "◼ Finaliza aquí",
      },

      // ═══════════════════════════════════════════════════════
      // SECCIÓN 4: PROCESAMIENTO GET YOUR GUIDE / CIVITATIS / VIATOR
      // ═══════════════════════════════════════════════════════
      {
        id: "cl-divider-3",
        type: "divider",
        title: "📨 Sección 4 — Procesamiento LLM (GYG / Civitatis / Viator)",
      },
      {
        id: "cl2-ggy",
        type: "decision",
        title: "¿Es Get Your Guide?",
        subtitle: "Detecta si el email proviene de Get Your Guide (modificaciones/cancelaciones)",
        api: ["n8n"],
        details: [
          "Filtro: From @getyourguide.com",
          "Asunto: modification, cancellation, change...",
          "Este email NO contiene código Turitop — solo referencia GYG",
          "Siempre va entre 2 emails Turitop (original → GYG → actualización)",
        ],
      },
      {
        id: "cl2-ggy-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Get Your Guide",
        title: "LLM Procesar GYG",
        subtitle: "Email de modificación detectado. Se procesa con Gemini para extraer datos.",
        api: ["IA", "n8n"],
        continuation: "→ Siguiente: Guardar Clasificación",
      },
      {
        id: "cl2-ggy-no",
        type: "branch_no",
        branchLabel: "NO — Evaluar Civitatis",
        title: "¿Es Civitatis?",
        subtitle: "No es GYG. Se comprueba si el email viene de Civitatis.",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Es Civitatis?",
      },
      {
        id: "cl2-civitatis",
        type: "decision",
        title: "¿Es Civitatis?",
        subtitle: "Detecta emails de Civitatis (cancelaciones principalmente)",
        api: ["n8n"],
        details: [
          "Filtro: From @civitatis.com",
          "Asunto: Reserva cancelada...",
          "Referencia externa contiene código Turitop (C731-G193-XXXXXX-X)",
          "Vinculación directa por G193 en referencia externa",
        ],
      },
      {
        id: "cl2-civitatis-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Civitatis",
        title: "LLM Procesar Civitatis",
        subtitle: "Email de Civitatis. Se procesa con Gemini para extraer cancelación y código Turitop.",
        api: ["IA", "n8n"],
        continuation: "→ Siguiente: Guardar Clasificación",
      },
      {
        id: "cl2-civitatis-no",
        type: "branch_no",
        branchLabel: "NO — Evaluar Viator",
        title: "¿Es Viator?",
        subtitle: "No es Civitatis. Se comprueba si el email viene de Viator.",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Es Viator?",
      },
      {
        id: "cl2-viator",
        type: "decision",
        title: "¿Es Viator?",
        subtitle: "Detecta emails de Viator",
        api: ["n8n"],
        details: [
          "Filtro: From @viator.com",
          "Asunto: Your booking details...",
          "Viator llega como email Turitop (no-reply@turitop.com) con bloque VIATOR ADDITIONAL INFO",
          "Se procesa por LLM para extraer booking reference y datos del cliente",
        ],
      },
      {
        id: "cl2-viator-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Viator",
        title: "LLM Procesar Viator",
        subtitle: "Email de Viator. Se procesa con Gemini para extraer datos.",
        api: ["IA", "n8n"],
        continuation: "→ Siguiente: Guardar Clasificación",
      },
      {
        id: "cl2-viator-no",
        type: "branch_no",
        branchLabel: "NO — Ignorar",
        title: "Ignorar email",
        subtitle: "No coincide con ninguna plataforma soportada. El email se ignora.",
        api: [],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "cl5",
        type: "action",
        title: "LLM Procesar Email (Gemini)",
        subtitle:
          "Analiza el contenido del email de GYG/Civitatis/Viator con Gemini para extraer código de referencia, tipo de modificación y datos.",
        api: ["IA", "n8n"],
        details: [
          "Modelo: Google Gemini (gemini-1.5-flash)",
          "Input: cuerpo completo del email",
          "Output JSON: { reference_code, modification_type, customer_name, tour_name, tour_code, event_date_original, event_date_new, people, turitop_code }",
          "GYG: vinculación por customer_name + tour + fecha (sin código Turitop)",
          "Civitatis: referencia externa contiene G193 (vinculación directa)",
          "Viator: bloque VIATOR ADDITIONAL INFO contiene booking reference",
        ],
        continuation: "→ Siguiente: Guardar Clasificación en Sheet",
      },
      {
        id: "cl-save-classification",
        type: "action",
        title: "Guardar Clasificación en Sheet",
        subtitle:
          "Registra el resultado del LLM en el Sheet clasificación_emails para trazabilidad.",
        api: ["Google Sheets", "n8n"],
        details: [
          "Sheet: clasificación_emails",
          "Campos: message_id, source (gyg/civitatis/viator), subject, reference_code, customer_name, tour_code, event_date, people, modification_type, old_date, new_date, status=classified",
        ],
        continuation: "→ Siguiente: Lookup Reserva Activa",
      },
      {
        id: "cl-lookup",
        type: "action",
        title: "Lookup Reserva Activa",
        subtitle:
          "Busca en Sheet reservas si existe una reserva activa con el mismo customer_name + tour_code + fecha (±1mes)",
        api: ["Google Sheets", "n8n"],
        details: [
          "Sheet: reservas",
          "Búsqueda: customer_name + status=active",
          "Filtro adicional en Code node: tour_code + fecha dentro de ±1mes",
          "Output: { booking_id, people, tour_code, event_date, calendar_event_id }",
        ],
        continuation: "→ Siguiente: ¿Reserva encontrada?",
      },
      {
        id: "cl-lookup-found",
        type: "decision",
        title: "¿Reserva encontrada?",
        subtitle:
          "Verifica si se encontró una reserva activa vinculable.",
        api: ["n8n"],
        details: [
          "Condición: booking_id existe y no está vacío",
          "Si SÍ → verificar si es cancelación o modificación",
          "Si NO → notificar sin referencia",
        ],
      },
      {
        id: "cl-lookup-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Encontrada",
        title: "¿Es Cancelación?",
        subtitle: "Determina si el email de la plataforma es una cancelación o modificación.",
        api: ["n8n"],
        continuation: "→ Siguiente: ¿Es Cancelación?",
      },
      {
        id: "cl-lookup-no",
        type: "branch_no",
        branchLabel: "NO — Sin referencia",
        title: "Notificar sin referencia",
        subtitle: "No se encontró reserva activa vinculada. Se notifica al equipo para revisión manual.",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Asunto: [SIN REFERENCIA] {source} — {reference_code}",
          "Contenido: referencia, cliente, tour, fecha",
          "Acción: El equipo debe localizar la reserva manualmente",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "cl-is-cancel",
        type: "decision",
        title: "¿Es Cancelación?",
        subtitle:
          "Según la clasificación del LLM, determina si es cancelación o modificación.",
        api: ["n8n"],
        details: [
          "modification_type = 'cancel' → Marcar cancelada, eliminar Calendar",
          "modification_type = 'modify' → Marcar superseded, esperar 2º Turitop",
        ],
      },
      {
        id: "cl-cancel-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Cancelación",
        title: "Marcar Cancelada + Eliminar Calendar",
        subtitle:
          "La reserva original se marca como cancelled en Sheet. El evento de Calendar se elimina.",
        api: ["Google Sheets", "Google Calendar", "Email"],
        details: [
          "Sheet reservas: UPDATE SET status='cancelled' WHERE booking_id=X",
          "Calendar: DELETE evento por calendar_event_id",
          "Notificar: [CANCELACIÓN] Reserva {booking_id} cancelada via {source}",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "cl-modify-yes",
        type: "branch_no",
        branchLabel: "NO — Es modificación",
        title: "Marcar Superseded + Notificar",
        subtitle:
          "La reserva original se marca como superseded. Cuando llegue el 2º email Turitop, se actualizará Calendar automáticamente.",
        api: ["Google Sheets", "Email", "n8n"],
        details: [
          "Sheet reservas: UPDATE SET status='superseded', gyg_reference='{ref}' WHERE ...",
          "Notificar: [MODIFICACIÓN] Reserva {booking_id} — change via {source}",
          "El calendario se actualizará cuando llegue el 2º email Turitop",
          "El 2º Turitop es detectado por cl-replace en Sección 3",
        ],
        continuation: "◼ Finaliza aquí — Esperando 2º email Turitop",
      },
    ],
  },
  {
    id: "04",
    title: "Panel Rentabilidad",
    description:
      "Dashboard Next.js + React para análisis de rentabilidad por tour y período.",
    icon: "📊",
    apis: ["Turitop", "Next.js"],
    tabs: [
      {
        id: "summary",
        name: "Resumen Global",
        icon: "📈",
        items: [
          { label: "Filtro selector de fechas", type: "Required" },
          { label: "Facturación Total", type: "Sum" },
          { label: "Gasto Total", type: "Sum" },
          { label: "Beneficio Total", type: "Calc" },
          { label: "Número de Reservas", type: "Count" },
          { label: "Número de Personas", type: "Sum" },
          { label: "Ratio Personas/Reserva", type: "Calc" },
        ],
      },
      {
        id: "by-tour",
        name: "Por Tour",
        icon: "🎯",
        items: [
          { label: "Selector de Tour", type: "Required" },
          { label: "Selector de fecha", type: "Required" },
          { label: "Facturación Tour", type: "Filter" },
          { label: "Gasto Tour", type: "Filter" },
          { label: "Beneficio Tour", type: "Calc" },
          { label: "Nº Reservas Tour", type: "Filter" },
          { label: "Nº Personas Tour", type: "Filter" },
          { label: "Ratio Personas/Reserva", type: "Calc" },
        ],
      },
    ],
    models: [
      {
        name: "Reservas (Turitop)",
        icon: "📋",
        fields: [
          { name: "id", type: "string" },
          { name: "tour_code", type: "WT, TT, TM..." },
          { name: "date", type: "date" },
          { name: "people", type: "number" },
          { name: "total_price", type: "number" },
          { name: "status", type: "confirmed/cancelled" },
        ],
      },
      {
        name: "Gastos (Manual)",
        icon: "💰",
        fields: [
          { name: "id", type: "string" },
          { name: "tour_code", type: "WT, TT, TM..." },
          { name: "amount", type: "number" },
          { name: "category", type: "guías, transporte..." },
          { name: "date", type: "date" },
          { name: "description", type: "string" },
        ],
      },
    ],
  },
  {
    id: "05",
    title: "Respuesta Guía",
    description:
      "Webhook que recibe las respuestas de los guías (WhatsApp/Email) + sistema de timeout con cron para detectar faltas de respuesta.",
    icon: "💬",
    apis: ["n8n", "WhatsApp", "Email", "n8n_database"],
    steps: [
      {
        id: "r-divider-1",
        type: "divider",
        title: "🖥 Rama Webhook — Respuesta del Guía",
      },
      {
        id: "r1",
        type: "trigger",
        title: "Webhook Respuesta Guía",
        subtitle: "Recibe la respuesta del guía via WhatsApp o Email tras solicitar confirmación",
        api: ["WhatsApp", "Email", "n8n"],
        details: [
          "Endpoint: POST /webhook/respuesta-guia",
          "Body esperado: { guia_id, tour_id, respuesta: 'SÍ' | 'NO' }",
          "Origen: Evolution API (WhatsApp) o Email parser",
          "Canal configurable: WhatsApp y/o Email",
        ],
        continuation: "→ Siguiente: Filtrar ¿es guía?",
      },
      {
        id: "r1-b",
        type: "decision",
        title: "Filtrar BD: ¿Corresponde a un guía?",
        subtitle: "Busca el email/teléfono del remitente en la BD de guías. Solo se procesa si está registrado.",
        api: ["n8n_database", "n8n"],
        details: [
          "Query BD: SELECT * FROM guias WHERE email = {remitente} OR telefono = {remitente}",
          "Si existe registro → es guía registrado → continuar flujo",
          "Si no existe → el mensaje no es de un guía → ignorar",
          "Output: { es_guia: bool, guia_info: { id, nombre, email, telefono } }",
        ],
      },
      {
        id: "r1-b-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Es guía",
        title: "Es guía, continuar flujo",
        subtitle: "El remitente está registrado como guía. Se procede a procesar su respuesta.",
        api: ["n8n"],
        continuation: "→ Siguiente: LLM Procesar respuesta",
      },
      {
        id: "r1-b-no",
        type: "branch_no",
        branchLabel: "NO — No es guía",
        title: "Ignorar mensaje",
        subtitle: "El remitente no corresponde a ningún guía registrado. El mensaje se descarta.",
        api: ["n8n"],
        details: [
          "Acción: no procesar, no responder",
          "Posible logging: registro de intento no autorizado",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "r1-c",
        type: "action",
        title: "LLM Procesar respuesta",
        subtitle: "Analiza el contenido del mensaje con IA para determinar si el guía confirma o rechaza",
        api: ["IA", "n8n"],
        details: [
          "Input: contenido del mensaje (texto del WhatsApp o Email)",
          "Prompt: 'Analiza este mensaje de un guía turístico. Responde SÍ si confirma disponibilidad, NO si rechaza. Mensaje: {contenido}'",
          "Output: { respuesta_llm: 'SÍ' | 'NO', confianza: 0-100 }",
          "Si confianza < 70% → notificar internamente para revisión manual",
        ],
        continuation: "→ Siguiente: ¿SÍ o NO?",
      },
      {
        id: "r2",
        type: "decision",
        title: "Procesar respuesta: ¿SÍ o NO?",
        subtitle: "Determina si el guía confirmó o rechazó basándose en el análisis del LLM",
        api: ["n8n"],
        details: [
          "Input: respuesta_llm del paso LLM Procesar respuesta",
          "Si respuesta_llm = 'SÍ' → Quitar paréntesis en Calendar + notificar",
          "Si respuesta_llm = 'NO' → Marcar no disponible en BD",
          "Si confianza < 70% → derivar a revisión manual interna",
          "Si timeout → Misma lógica que NO",
        ],
      },
      {
        id: "r2-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Confirmó",
        title: "Quitar () en Calendar y notificar",
        subtitle: "Quita los paréntesis del código guía en Google Calendar y notifica al equipo",
        api: ["Google Calendar", "Email", "n8n_database"],
        details: [
          "Google Calendar: actualizar título, quitar paréntesis del código guía",
          "BD: estado = confirmado",
          "Notificar internamente: guía [nombre] confirmado para [tour] [fecha]",
        ],
        continuation: "◼ Finaliza aquí",
      },
      {
        id: "r2-no",
        type: "branch_no",
        branchLabel: "NO — No disponible",
        title: "Marcar no disponible en BD",
        subtitle: "El guía rechazó o no respondió. Se registra en BD y se evalúa siguiente paso",
        api: ["n8n_database", "n8n"],
        details: [
          "BD: estado = no_disponible",
          "¿Quedan guías pendientes en la lista?",
          "  SÍ → Contactar siguiente guía",
          "  NO → Notificar todos declinan",
        ],
        continuation: "→ Siguiente: ¿Quedan pendientes?",
      },
      {
        id: "r-divider-2",
        type: "divider",
        title: "⏰ Rama Cron — Timeout cada 1h",
      },
      {
        id: "r4",
        type: "trigger",
        title: "Cron Timeout (cada 1h)",
        subtitle: "Schedule que se ejecuta cada hora para detectar guías sin respuesta",
        api: ["n8n"],
        details: [
          "Trigger: Schedule (cron: 0 * * * *)",
          "Objetivo: detectar guías que no han respondido dentro del timeout",
        ],
        continuation: "→ Siguiente: Consultar BD",
      },
      {
        id: "r5",
        type: "action",
        title: "Consultar BD registros pendientes",
        subtitle: "Obtiene de n8n_database todos los registros con estado = 'pendiente' para calcular diff horaria",
        api: ["n8n_database", "n8n"],
        details: [
          "Query: SELECT * FROM registros WHERE estado = 'pendiente'",
          "Por cada registro se ejecutará el JS Code para calcular diffHoras",
          "Campos necesarios: timestamp_envío, timeout_horas, guia_id, tour_id",
        ],
        continuation: "→ Siguiente: JS Calcular diff",
      },
      {
        id: "r6",
        type: "action",
        title: "JS: Calcular diff horas vs timeout",
        subtitle: "Por cada registro, calcula si ha pasado el tiempo de espera configurado",
        api: ["n8n"],
        details: [
          "Código JS (n8n Code Node):",
          "",
          "const diffHoras = (now - timestamp_envío) / (1000 * 60 * 60);",
          "const timeout = timeout_horas; // 6, 12, 24 o 48",
          "",
          "if (diffHoras >= timeout) {",
          "  // Marcar como timeout",
          "  // Estado = 'timeout'",
          "  // Ejecutar flujo de 'no disponible'",
          "} else {",
          "  // Aún no ha pasado el tiempo",
          "  // No hacer nada, esperar próximo cron",
          "}",
          "",
          "Timeout configurable por actividad o global:",
          "  Por defecto: 24h",
          "  Opciones: 6h / 12h / 24h / 48h",
        ],
        continuation: "→ Siguiente: ¿Timeout alcanzado?",
      },
      {
        id: "r7",
        type: "decision",
        title: "¿Timeout alcanzado?",
        subtitle: "Comprueba si diffHoras >= timeout_horas para algún registro",
        api: ["n8n"],
        details: [
          "Condición: diffHoras >= timeout_horas",
          "Si SÍ → marcar como timeout, ejecutar flujo 'no disponible'",
          "Si NO → esperar próximo ciclo del cron",
        ],
      },
      {
        id: "r7-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Sin respuesta",
        title: "Marcar timeout y evaluar siguiente guía",
        subtitle: "Se marca el registro como timeout en BD y se ejecuta la misma lógica que respuesta = NO",
        api: ["n8n_database", "n8n"],
        details: [
          "BD: estado = 'timeout'",
          "Misma lógica que rama NO: ¿Quedan guías pendientes?",
          "  SÍ → Contactar siguiente guía automáticamente",
          "  NO → Enviar notificación 'Todos declinan'",
        ],
        continuation: "→ Siguiente: ¿Quedan pendientes?",
      },
      {
        id: "r7-no",
        type: "branch_no",
        branchLabel: "NO — Aún esperando",
        title: "Esperar próximo ciclo",
        subtitle: "El tiempo de espera no ha vencido. Se espera al próximo cron (1h) o a la respuesta del guía.",
        api: ["n8n"],
        continuation: "◼ Finaliza aquí (espera 1h)",
      },
      {
        id: "r-divider-3",
        type: "divider",
        title: "🔁 Flujo Compartido — Gestión del Siguiente Guía",
      },
      {
        id: "r3",
        type: "decision",
        title: "¿Quedan guías pendientes?",
        subtitle: "Verifica si hay más guías en la lista de pendientes para contactar",
        api: ["n8n", "n8n_database"],
        details: [
          "Consulta la lista de guías pendientes del tour",
          "Si SÍ → contactar al siguiente guía",
          "Si NO → notificar que todos declinan",
        ],
      },
      {
        id: "r3-yes",
        type: "branch_yes",
        branchLabel: "SÍ — Siguiente disponible",
        title: "Contactar siguiente guía",
        subtitle: "Envía mensaje al siguiente guía de la lista (WhatsApp o Email) y registra nuevo timestamp en BD",
        api: ["WhatsApp", "Email", "n8n_database", "n8n"],
        details: [
          "Canal: WhatsApp (Evolution API) o Email",
          "Registrar en BD: nuevo registro con estado = 'pendiente'",
          "Campos: guia_id, tour_id, timestamp_envío=now, estado=pendiente, timeout_horas",
        ],
        continuation: "◼ Finaliza aquí (espera respuesta)",
      },
      {
        id: "r3-no",
        type: "branch_no",
        branchLabel: "NO — Sin guías disponibles",
        title: "Notificar todos declinan",
        subtitle: "Todos los guías han rechazado o no respondido. Se envía alerta al equipo.",
        api: ["Email"],
        details: [
          "Para: equipo@gourmetmadrid.com",
          "Asunto: [URGENTE] Sin guía disponible para [tour] [fecha]",
          "Acción: El equipo debe encontrar un guía manualmente",
        ],
        continuation: "◼ Finaliza aquí",
      },
    ],
  },
];

export default PROJECTS;